### PR TITLE
removed unnecessary HTML entity

### PR DESCRIPTION
**Pull request by DanielRuf**
I hope it's okay because we don't use `&nbsp;` anywhere and it might be unnecessary.

### CODE REVIEW

**Comment by Maikuolan** [comment]
Uh oh.. I think I might've misunderstood when [you asked me](https://github.com/Maikuolan/phpMussel/pull/18) about this earlier; Because there were two `&nbsp;` entities in the German translation, whereas every other language file only had one of them (which was a typo; there should've only been one), and you corrected it, I thought your question was confirming that the correction was okay (my fault for replying while tired and not being clear).

As for the entity being required at all, I put it in there originally to forcibly prevent word-wrapping where the variable is [being parsed](https://github.com/Maikuolan/phpMussel/blob/master/vault/template.html#L39):
`<span style="color:#000000;">&nbsp;{generated_by}&nbsp;</span><span style="color:#ff0000;">{phpmusselversion}</span>`

I thinking I'd like to keep them in there for that reason (but only for `generated_by`; having it in any other variables would, of course, be unnecessary).

Sorry about that. :-/

**Comment by DanielRuf** [comment]
Ah ok, this makes sense. Sorry for the commits and pull request. I will revert/delete them.

**Comment by DanielRuf** [comment]
@Maikuolan But we could use `white-space: nowrap;` in CSS to prevent breaking lines and can safely remove the `&nbsp;`. If this is ok (for me this is the best solution, so we really separate HTML and the actual text/translation) I will create a new pull request and make also the change to the CSS/HTML code.

**Comment by Maikuolan** [comment]
Good point; That sounds like an obvious alternative, but I hadn't considered it before. :?

Now I'm wondering which way would be best?
- Using CSS `white-space: nowrap;` would likely be more standards compliant, and likely a more commonly accepted practice, but in practice, both ways seem to work equally as well as each other.
- If I nitpick the choice, then, `&nbsp;` -possibly- may be more widely supported, in the sense that using entities in this way is much older than the use of `white-space: nowrap;` and will likely be supported by those browsers that don't support `white-space: nowrap;`, but, seeing as that sort of CSS has been around since CSS2, I highly doubt that situation is likely to arise too frequently.
- Bandwidth difference is very negligible; If I use `&nbsp;` both in the variables (which uses 1 such entity) and in the template file (which uses 2 such entities), it'll cost 18 bytes, whereas if I use `white-space: nowrap;`, it'll cost 19 bytes (I already have a `<span` I could use in the template file). One byte of difference.
- CSS would be more consistent, seeing as I'm already using CSS for other things, but this is the only thing I'm using entities for in the entire project at the point.
- Although I don't think it makes too much difference, using CSS instead of entities would mean we could remove the entities from the language files, and that -might- make the job of translating easier for translators. It'll certainly look cleaner. Possibly may be perceived as more professional by some people, too, but I don't know; Probably not much difference there.

I can't really think of any other immediate considerations, and the pros and cons seem reasonably balanced. I like having good reasons for doing things, but, I think this may ultimately come down to opinion.. And I honestly don't mind too much either way, although I do think it would be good to have a decision one way or the other.

..What do you think? XD

If you think it'd be better with CSS, want to add that in to the `template.html` file and then reopen/recreate this pull request? I'll merge it through.

**Comment by DanielRuf** [comment]
In my opinion HTML code should not be in the text for the translations. `white-space` is a CSS1 feature ;-)

http://www.w3.org/TR/REC-CSS1/#white-space

Here you can see that it works without any problems (I do not use any `&nbsp;`): https://jsfiddle.net/ygwz7f8z/

**Comment by Maikuolan** [comment]
Alright, sounds good; We'll ditch the entities and use `white-space` instead. XD

**Pull request closed without merging**
