### PR TITLE
updated german readme

### PR DESCRIPTION
**Pull request by DanielRuf**
We have to reformat the readme to use the right length for each line.
If there is some description how you do this (eg with a specific editor), please let me know, so I can do this myself in the future and improve the overall quality with the right tools.

Work on other translations will be started very soon.

### CODE REVIEW

**Comment by Maikuolan** [comment]
Thanks for your work. :-)

I haven't yet written any formal descriptions or guidelines anywhere on how I'm doing this (I probably should do that though).

I need to leave the house in a few minutes to meet with some people, but I'll write up some rough guidelines as soon as I'm back again (should be within a few hours from now).

**Comment by DanielRuf** [comment]
No hurry.
Ok, this would be very helpful.

Next points on my todo list are: 
- [ ] invite translators for translation audit (https://github.com/Maikuolan/phpMussel/issues/3)
- [ ] create new translations with translators using your guideline
- [ ] create deployment solution for testaccount (https://github.com/Maikuolan/phpMussel/pull/14)

**Comment by Maikuolan** [comment]
Although I'm very late with it (last minute changes to my schedule), I've written up some basic guidelines. I'm also wondering if perhaps I should post these guidelines somewhere else? Maybe I should make use of the Wiki feature of GitHub? I haven't yet explored the Wiki feature and I'm unsure whether or not it's worth the time and effort. I'm curious to know how you feel about that idea.

Anyhow, what I've written (written in a non-targeted manner, so that it could apply to anyone):

---

**General guidelines for editing and/or translating the phpMussel documentation (these guidelines are intended to assist those that may be interested in editing and/or translating the phpMussel documentation to do so in what I'd personally consider the optimal manner, but they shouldn't be regarded as strictly enforced rules; If they help you work, use them, but if they hinder you, don't worry about them; I'm quite happy to get whatever help I can with this sort of work in whatever way people are willing to offer):**

**Permissions:** Anyone is able to edit and/or translate the phpMussel documentation. If you're registered with GitHub, just fork a copy a of the project, open the files to be edited in your preferred editor of choice (I personally recommend Notepad++, but almost any plain-text editor will suffice), do whatever editing you're interested in doing, and when you're done, send a pull request back to the main project. I'll take a look at the changes that've been made, and if your updated file looks better, more accurate or more complete than whatever is already there, I'll be more than likely to accept your pull request with the updated documentation. Alternatively, if you aren't registered with GitHub, just download the necessary files from the repository, edit them on your local machine and then send them to me through whatever means is convenient, whether that be email, FTP, filesharing or otherwise, and again, I'll take a look at them (just don't make it difficult by sending them in a way that requires me to download and install thirdparty, proprietary or suspicious software that I'm not familiar with). One of the major benefits of using GitHub to do this, of course, is in how much easier collaboration becomes for developers by using GitHub, and additionally, by sending me your changes through GitHub, there'll be a historical record of the work that you've done within the commit history.

**Documentation layout and internal file structure:** Because there are already README files existing within the collective documentation, you shouldn't need to be writing new layouts or new internal file structures, because they'll already be there available to you within those README files that already exist, and it also shouldn't be necessary for me to describe what's desired or for us to determine a consensus. Just take a look at the layout and internal file structure of those already existing README files and use what's already available if you're unsure about it, or, if you actually want to come up something new, you're welcome to do so (though, that doesn't necessarily mean that I'll agree with or accept what you do, but, I'd be willing to take a look at it anyhow). If you wish to write or include additional content to the documentation, in regards to layout and internal file structure, use your best judgment. If it works, I'll attempt to mirror it across all documentation, and if it doesn't work, I'll find a way to make it work.

**Formatting:** All README files are written in BOM-less UTF-8 plain-text TXT files. You're welcome to write additional documentation in other formats if you wish to, but, the core README files will always remain as that format.

**Line length and paragraph formatting:** I've opted to limit the maximum line length of any lingual-content to 80 characters (I define lingual-content as anything written in any particular spoken or written language intended for display and reading on a screen; By that definition, lingual-content is the majority of the content of all README files, and a certain very small selection of lines from within the "lang.??.inc" files). I felt there needed to be some sort of limit in place as a means to improve readability, intelligibility and aesthetics of the lingual-content of phpMussel, and because I didn't want those reading the documentation to be forced to used word-wrap to be able to read it properly when there are certain text readers and screen readers that don't have the ability to correctly word-wrap. This, of course, would require determining what the limit should actually be. My primary reasons for choosing a 80 character length limit were that I found that most of those text readers and screen readers that can't correctly word-wrap (though not 100% of them, admittedly) that I had the opportunity to test properly, tended to have a display width of approximately that same length, and that MS-DOS/CMD also had that same display width (which is what would be used for running phpMussel in CLI-mode under Windows by whatever small number of Windows users using phpMussel in CLI-mode there might've been). I've also since found that it seems to be a reasonably common choice of line length limit (although not an official nor a defacto standard) amongst various other projects that've had plain-text README files in the same manner that phpMussel does. As a caveat to this limitation, code examples or any non-lingual-content contained within the documentation shouldn't ever be broken, even if they surpass this limit, due to the risk of decreasing the readability or intelligibility of those code examples and the risk of anyone that might make use of those code examples replicating those same linebreaks within a live deployment. With the aforementioned in consideration, documentation generally should be structured (including in regards to line length) in whatever way is going to provide the best level of readability and intelligibility for the end-user reading that documentation (for example, by trying to fit as much as possible onto each line as to reduce on unnecessary whitespace and reduce the amount of scrolling required by the end-user to read the documentation, and by using single-line spacing between separate paragraphs and double-line spacing with clear breaks between separate sections to make it easier to clearly distinguish between unique sections of the documentation and to give clear context to unique paragraphs, and by using consistent margins); This, of course, could be highly subjective, because exactly what constitutes "best" could depend on the views and opinions of the reader and writer alike, but, I trust you to use your best judgment, and unless something is incredibly wrong in an incredibly obvious way, generally speaking, I'll trust your judgment in regards to the matter and you have a good level of leeway.

_Regarding line length, a few interesting reads for those interested in the subject:_
- http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width
- http://stackoverflow.com/questions/578059/studies-on-optimal-code-width

**Proof-reading:** If you're not sure how to write something correctly, try to check it, and always proof-read your work to reduce the chances of easily avoidable errors being mainlined to the master repository (errors do happen, and you won't be hounded for it, but, proof-reading should reduce these errors somewhat).

**Tabs vs Spaces:** I always spaces (\x20) for the documentation and I always use tabs (\x09) for the actual scripts and actual code. Whether this is the best choice, is something that could be easily argued, but this choice is what I've been using for this project for a long time now, so, unless I can find a good reason to change that choice, I'd like to stick to it. My main reasoning here, again, basically comes down to readability and intelligibility - I find spaces easier to work with for the documentation and I find tabs easier to work with for the code. If you find sticking by this to be difficult, don't worry too much, because I can still accept your work and then just make the necessary modifications myself; It literally takes me about 3 seconds to make the change using the search-and-replace function of Notepad++.

**Linebreaks:** The question of whether to use CR, LF, CR+LF, LF+CR, RS, \x9b or something else, is another subject that could be readily argued by those that care about it (though I strongly suspect that most people probably don't). From the perspective of standards, Windows-based machines tend to prefer CR+LF, Unix-based machines tend to prefer LF, Mac-based machines tend to prefer CR, and there are certain other machines that have other, more obscure standards (although any good program made by a developer that understands this, should be able to handle files using any of those standards equally well). Although I personally work from a Windows machine, I've opted to use LF for breaking lines in the documentation for phpMussel (as well as all other files within the phpMussel project), because, for me, from a digital/computering viewpoint, I think it makes more sense (from a non-digital standpoint such as with Typewriters and other older systems, probably, I think LF+CR would make more sense). In terms of how it makes "more sense", it just comes down to sematics and the descriptions of what the different types of linebreaks are and how they're actually supposed to work. If you don't use what I use, during the course of my reviewing your work, I'll likely just end up editing to conform to what I do without much thought to it, but it really doesn't actually matter either way, I think, but, I make mention of my choice of linebreaks, because, for the sake of keeping to some sort of standard, I've made a choice, and therefore feel it should be mentioned, even if it isn't particularly important. If you disagree with my choice, you're welcome to share with me your reasons why you disagree; Seeing as I don't think it's too important, I might be convinced to change my choice without too much difficulty.

_Reference: http://en.wikipedia.org/wiki/Newline_

**EOF:** "EOF" is an acronym for "End of File". I write this at the end of all README files (on a newline, by itself, without any other data), simply as a way of clearly and visually marking that that point is the actual end of the file. It's not too important, but, some people like it and I've seen it used in documentation elsewhere, and so, I'd started doing it myself, and since starting to do it, I've grown accustomed to it. Because EOF indicates the end of the file, logically, there shouldn't be any data whatsoever following after EOF.

**Timestamping:** At the end of all README files (but prior to the EOF), there'll be a "Last Edited" timestamp (to indicate when a particular file was last modified/edited). Although not particularly important when rapid changes are being made over a brief period of time, ideally, I'd like editors/translators to update that timestamp to the current date at the time of editing whenever changes are made.

**Verifiability of content and conflicts of opinion:** Everything is always open for debate, and if a conflict of opinion emerges, I'm always interested to hear all sides and all opinions. However, that said, if, in the course of translating documentation or updating translations, a conflict of opinion emerges between a native speaker of a particular language and a non-native speaker of a particular language, unless there is good evidence shown to me that I shouldn't do so, I'll always side with the native speaker, under the assumption that the native speaker will know more about their own language than a non-native speaker would. The same goes for fluency versus non-fluency, and experience versus non-experience; In such an event, unless there is good evidence shown to me that I shouldn't do so, I'll always side with the person that has the greater level of fluency and/or experience. I don't exempt myself from this: As it happens, although I have some limited experiences with other languages, my native language is English and English is the only language that I speak fluently, and, although I do have some limited experience in translating documentation, all my experience is entirely on a hobbyist level, rather than a professional level.

If anyone has any suggestions for changes to be made to these guidelines or if anyone wishes to append additional information to these guidelines, let me know.

Kind Regards,
Caleb M / Maikuolan.

**Comment by DanielRuf** [comment]
Thanks for the very detailed and helpful guide.

In my opinion the Wiki is very helpful as you do not have to add the contents to the actual repository and its files but have the separate Wiki which is not part of the main git repository when downloaded, they are separate git repositories.

https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

So things like this guideline and other information for contributors would be in a central place (the Wiki) and do not clutter the actual repository.

The Wiki supports many markups like markdown (which you may have already used here in the comments), HTML and so on.

https://help.github.com/articles/about-github-wikis/

When I work on GitHub projects I often read the documentation, which is in most cases in the Wiki or on a GitHub page, where many questions, guidelines and more information are held for the contributors and developers on GitHub.

Just some example Wikis:
https://github.com/showcases/projects-with-great-wikis
https://github.com/jquery/jquery/wiki
https://github.com/Modernizr/Modernizr/wiki
https://github.com/mbostock/d3/wiki
https://github.com/h5bp/html5-boilerplate/wiki

**Comment by Maikuolan** [comment]
_Referenced via https://github.com/Maikuolan/phpMussel/wiki/Dev:Guidelines:Documentation_

**Comment by Maikuolan** [comment]
Cheers. :-)

I'll have a look through some of those and try to use them as guidelines for working on the Wiki.

**Comment by DanielRuf** [comment]
Awesome, thanks =)

**Pull request merged**
